### ISSUE TITLE
päivitä koodi ei-Heroku -todellisuuteen

### ISSUE THREAD

**Issue by samiheinanen** [KosmosRy/puraisin#10]
Nyt Heroku-mystisiä system.env -muuttujia, vai voikohan jättää noin jos vaan päivittää env. rivejä vastaamaan uusia yhteyksiä esimerkiksi? en tiedä mitkä on aws:n possut osoitteet ja kredentiaalit.

noh yhtä kaikki voisi kirjoittaa skrädestä vielä kerran elegentimmaksi.

**Comment by tjjalava** [comment]
sun ei tarvitse paikallisessa devauksessa tietää tai välittää aws:n possun tiedoista mitään. Aseta ne vastaamaan oman kehitysympäristösi vastaavia osoitteita. Eli koodi on ihan ok noin.

Eli ennen kuin ajat "node index.js", aseta ympäristömuuttujiin sopivat arvot PORT- ja DATABASE_URL-muuttujille
