### ISSUE TITLE
Varoitus toistuvista ensipuraisuista saman puraisuvuorokauden aikana

### ISSUE THREAD

**Issue by stoivane** [KosmosRy/puraisin#11]
Puraisimen pitäisi varoittaa käyttäjää, jos tämä on epähuomiossa lisäämässä saman puraisuvuorokauden aikana toisen ensipuraisun.

Toinen vaihtoehto on estää ylimääräiset ensipuraisut tykkänään. Tässä tapauksessa on luontevaa poistaa koko ensipuraisu-vaihtoehto valinnoista kuluvan puraisuvuorokauden ajaksi, kun ensipuraisu on raportoitu kertaalleen.

**Comment by tjjalava** [comment]
tämä vaatii vähän spekausta. Puraisuvuorokausihan on perinteisesti alkanut klo. 3.30, mutta muuttuuko tämä uuden alkoholilain myötä maaliskuussa, jolloin alkoholia saa laillisesti tarjoilla klo. 4:ään saakka? Varmaan muuttuu.. 
Toinen ongelma onkin sitten muilla kuin Suomen aikavyöhykkeellä tapahtuvat puraisut. Otetaanko aikaero huomioon, eli lasketaanko ns. "paikallinen puraisuvuorokausi", vai mennäänkö globaalisti Suomen aikavyöhykkeen mukaan, niin, että esim. Australiassa puraisuvuorokausi alkaakin joskus iltapäivällä paikallista aikaa?

**Comment by tjjalava** [comment]
mites muuten, miten tunnistetaan formaalisti ensipuraisu? Jos tyyppi on "ep"? Entäs jos käyttäjä syöttää tyypiksi "ensipuraisu"? Vai pitäisikö puraisuvuorokauden ensimmäinen puraisu merkitä ensipuraisuksi implisiittisesti? Pitäisikö muiden puraisutyyppien olla disabloituina/aiheuttaa varoituksen kun on kyseessä p-vrk:n ensimmäinen puraisu? Onko munassa luita? Montako ikkunaa on Ruotsin kuninkaanlinnassa?

**Comment by tjjalava** [comment]
tää selvästi vaatii aika paljon lisää speksausta..

**Comment by jruuttun** [comment]
Katsoisin, että käyttäjällä on nyt liikaa vapautta puraisutyypin vapaasyötössä. Puraisutyyppi kylmästi koodistoksi vaan, rönsyily ja taiteellinen vaikutelma voisi tuottaa sitten esim. kommentti/lisätietokentissä. Puraisutyypin eheystarkistus voisi olla luontevasti vaikka postgresinCheck constaintina https://www.postgresql.org/docs/9.4/static/ddl-constraints.html tai triggerissä, ja toki sitten virhetilanteen ehkäisemiseksi ehkä käyttöliittymässäkin. Slackin puolella raportoitaessa pitäisi sitten osua olemassaolevaan puraisutyyppiin, mikä kieltämättä vähän vaikeuttaa vanhanmallista raportointia. Olisko tämä kuitenkin pienempi paha?

**Comment by tjjalava** [comment]
Mites se, jos merkkaa loppupuraisun, pitääkö silloin estää jatkopuraisut saman p-vrk:n aikana?

**Comment by samiheinanen** [comment]
Härifrån tvättas, sanoisi Bengt. Betoninkovaa speksin tynkää nimittäin debatin liekittämiseksi:

**Puraisuvuorokauden määritelmä**

_Vuorokauden kesto_
Puraisuvuorokausi alkaa aina YYYY-MM-DD 06:00:00.000 ja päättyy seuraavan vuorokauden puolella YYYY-MM-DD 05:59:59.999. Jos käyttäjän puraisusyötteestä saadaan aikavyöhyke UTC offsettinä (tarkkuus 1 tunti) TAI paikallinen puraisuaika, tallennetaan tämä puraisun yhteydessä timestamppina kera UTC offsetin. Mikäli paikallista aikaa ei saada syötteessä, tallennetaan puraisun aikaleima oletuksella UTC+02:00 (EET). 

*** vaikutukset: 
a) kannan tietotyypin formaatin tarkistaminen 
b) paikallisen ajan/aikavyöhykkeen pölliminen käyttäjän päätelaitteesta tai kanavasta riippumatta. Peukalosääntö: jos tietoa ei saada, fallback on UTC+2.

POIKKEUS: _Ylivuorokautiset rännit_
Yhteen puraisuvuorokauteen (PVK) mahtuu vain yksi ensipuraisu (ep). Vaikka seuraavan PVK:n puolella tehtäisiinkin edelliseen ränniin luettava puraisu, merkitään ko. PVK:n ensimmäinen puraisu ensipuraisuksi. Mikäli ensimmäisen PVK:n viimeisestä puraisusta on promillemääräisesti "höyryä jäljellä" seuraavan PVK:n ensipuraisuun, voidaan erehtymättömän algoritmin avulla ketjuttaa nämä PVK:t yhdeksi ränniksi raportointikerroksessa. Toisin sanoen, jokainen yksilöllinen puraisuvuorokausi on entiteetin PVK ilmentymä. Samalla täysin aukottomalla logiikalla voidaan kunkin PVK:n viimeinen puraisu "täsmätä väkivaltaisesti" (kirjanpitotermi) leimata loppupuraisuksi (lp), kuitenkin siten, että alkuperäinen puraisutyyppi säilytetään tietokannassa ja täsmäytykset ajetaan ATK:lla omaan sarakkeeseensa "puraisutyyppitäsmäytys" (PTT). 

*** vaikutukset: 
a) pitää toteuttaa etäisyyslasku (veren alkoholipitoisuus promilleina) puraisun ja edellisen puraisun välillä. Toisin sanoen, mikä on veren alkoholipitoisuus puraisun tallennusajankohtana (VAPTA). Tieto lasketaan ja tallennetaan joka puraisun yhtomaan sarakkeeseensa "verenalkoholipitoisuuspromilleina" (VAPP). 
b) "väkivaltaisten täsmäytysten" suunnittelu, implementointi ja testaus. Kantatriggeri, ohjelmallinen tarkistus joka puraisun yhteydessä tai jotain aivan muuta. 
c) mikäli uuden vuorokauden ep pn tehty ns. "juubelissa", käytetään tietokantaan luotavaa saraketta "jatkoränniin kuuluva puraisu" (JKP). Kaikki seuraavan vuorokauden puraisut, joiden aikana VAPTA > 0 saavat tämän kunnimerkinnän kylkeensä. 
d) lisäksi ketjun kommenteista poimitaan seuraava ehdotus toteutettavaksi: kun PVK:n ep on tehty, ep on disabloitu PVK:n loppuun asti. 

**Tiedon laatu**
Puraisutyypin raportoinnissa ATK:lle on vuohen mentävä aukko niin Slack-kanavan kuin Mopiili-ATK:n välityksellä. PVK:n ep voidaan täsmäyttää väkivaltaisesti käyttäen PTT-kenttää, muut puraisut eivät ole niin kriittisiä, vaan voivat olla mitä keijoa vaan leväperäisesti tarkasteltuna. jruuttun ehdotus riittävän kattavasta enumeraatio-henkisestä valintamahdollisuudesta olisi tiedon laadun kannalta toimivin. Slack-kanavan kautta tulevat raportit jäänevät jatkossa käyttötapauksen reunatapauksiksi. 

Kaikki kuvaileva tieto tallennetaan as it is, järjestelmä ei ole mikään totalitaarisen valtion kansalaisjournalismia estävä/rajoittava hökötys. Niin ikään puraisun sisällön tulee säilyä vapaana, vaikka suotavaa olisi, että Mopiili-ATK:n käyttöliittymässä sisältö-kentässä olisi ennakoiva tekstinsyöttö, joka osaltaa parantaisi tiedon laatua.

*** vaikutukset:
a) poistetaan "muu" -kenttä Mopiili-ATK:n käyttöliittymästä ja tuodaan tilalle riittävä määrä puraisutyyppejä, joilla katetaan harrastuneimmankin kupittajan perustarpeet. 
b) varaudutaan Slack-kanavan kautta tuleviin monimuotoisiin puraisutyyppi-ilmoituksiin luomalla sarake "puraisutiedonlaatuleima" (PLL), johon tallennetaan tieto, miten hyvin annettu puraisutyyppi vastaa viittausdatassa (referenssitaulu "puraisutyyppivariaatiot" (PTV)) olevia puraisutyyppejä. Esim. Levenshteinin etäisyyttä voidaan käyttää ja pisteyttää vapaamuotoisten puraisutyyppien osuvuus referenssidataa vasten. 
c) tutkitaan ennakoitavan tekstinsyötön uhkia ja mahdollisuuksia.

Tässä ensimmäinen drafti. Peli on auki, ja yritetään saada julistus yhteisesti sovituksi ennen vuotta 2034.

**Comment by tjjalava** [comment]
Heti pikainen vastaehdotus:

Korvataan käsite "puraisuvuorokausi" kokonaan käsitteellä "ränni":
Ränni alkaa ensipuraisusta ja jatkuu niin pitkään, kun puraisujen väli on n aikayksikköä (tai jos/kun alkoholilaskurimme tulkitsee alkoholiprosentin riittävän suureksi), tai kunnes raportoidaan loppupuraisu. Rännin aikana ensipuraisut estetään käyttöliittymässä. Jos kuitenkin sellainen onnistutaan esim. slackin kautta syöttämään, tulkitaan se normaaliksi puraisuksi raportointivaiheessa. 

Motivaationa tähän siis "puraisuvuorokauden" määrittelyn hankaluus/jäykkyys ja todellisuuden huono mallintuminen. PVK on myös loppujen lopuksi aika mielenkiinnoton tilastoitava verrattuna vaikkapa rännin pituuteen.

**Comment by stoivane** [comment]
Nyt pisti Jallu piloillaan väkevän ja raikkaan ehdotuksen! Yksinkertaista, eleganttia, mielenkiintoista ja toimivaa – kannatan.

**Comment by samiheinanen** [comment]
no mutta tuo lähestyminen ratkaisisi tosiaan monta ongelmaa. jos saadaan VAPTA laskettua hyvin. täytynee skissailla jotain runkoa
