### ISSUE TITLE
Juomakentän pituutta kasvatettava

### ISSUE THREAD

**Issue by stoivane** [KosmosRy/puraisin#18]
Nykyinen kentän pituus varchar(64) on liian lyhyt. Tosielämän esimerkki 64 merkkiä pitemmästä juomasta: ”To öl / Põhjala Taanilinn Cognac Barrel Aged Spiced Imperial Stout”.

Ehdotan, että pituudeksi pannaan suoralta kädeltä 128 merkkiä. Toivottavasti kentän pituus on muutenkin määritelty merkkeinä eikä tavuina.

**Comment by tjjalava** [comment]
korjattu
