### ISSUE TITLE
Autentikointi palveluun

### ISSUE THREAD

**Issue by tjjalava** [KosmosRy/puraisin#2]
Pitäisi selvittää onko mahdollista käyttää Slackin tunnuksia autentikoimaan puraisijat. Jos Slack ei tarjoa APIa tähän, jokin muu palvelu (Google/Facebook...) tilalle. Mieluimmin ei mitään omaa autentikointitoteutusta, salasanoja on jo muutenkin liikaa muistettavana

**Comment by tjjalava** [comment]
Autentikointi onnistunee slackin oauth-rajapinnan avulla.. kunhan joku jaksaa sen koodata käyttöön ;)

**Comment by samiheinanen** [comment]
Suljetaan, done

**Comment by tjjalava** [comment]
Tää olisi sulkeutunut automaattisesti ton OAuth-PR:n mukana, koska olin lisännyt sinne viittauksen tähän issueen. Githubin issue-viittaukset on aika mainio työkalu, kannattaa opetella
