### ISSUE TITLE
Site iconin lisääminen

### ISSUE THREAD

**Issue by stoivane** [KosmosRy/puraisin#24]
Puraisin tarvitsee arvoisensa site iconin / faviconin.

Ensin suunnitellaan hyvä ikoni (joka toimii myös pienikokoisena) ja sen jälkeen vaikka faviconit.comilla tehdään ”likainen työ”. https://stackoverflow.com/a/43154399

**Comment by tjjalava** [comment]
Olen tilannut ikonin osuuskunnan graafiselta osastolta jo kuukausia sitten, mutta ilmeisesti bäklogi on ollut siellä turhan täynnä. Ehkä heraldis-veksillologis-numismaattinen toimikunta voisi ottaa tästä pallon?

**Comment by stoivane** [comment]
Consider it done!

**Comment by samiheinanen** [comment]
Laitettu kanavalle kaksi versiota reposteltavaksi. T. HVN-valiokunta.

**Comment by samiheinanen** [comment]
![p-32x32](https://user-images.githubusercontent.com/12933669/38023270-80501410-328a-11e8-86b4-9a6607a10fd8.png)
![pp-32x32](https://user-images.githubusercontent.com/12933669/38023272-806c8028-328a-11e8-9360-f446a0a466ab.png)

**Comment by tjjalava** [comment]
äläs nyt vielä sulje, ei tämä vielä valmis ole
