### ISSUE TITLE
Estimoiva algoritmi

### ISSUE THREAD

**Issue by samiheinanen** [KosmosRy/puraisin#25]
Korvataan Erehtymätön Algoritmi (TM) Estimoivalla Algoritmilla (TM). 

-- ---------------
-- Stoori:
-- ---------------
Käyttäjänä haluan, että pikapuraisin kertoo minulle raporttini antamisen jälkeen, miten juovukkeessa (arviolta) olen parhaillaan käynnissä olevassa rännissä. 

-- ------------------------
-- Spexii:
-- ------------------------
* Ränni lasketaan alkavaksi käyttäjän edellisestä ensipuraisusta 
* Mukaan lasketaan kaikki puraisut em. puraisun jälkeen JA ensipuraisu tietty
* Oletetaan, että yksi puraisu = yksi standardiannos alkomahoolia (12g)
* Oletetaan, että puraisijan paino (miesten keskipaino) on 85,5 kg (LÄHDE: https://www.mtv.fi/lifestyle/hyvinvointi/artikkeli/tallaisissa-mitoissa-keskivertosuomalainen-on-tarkista-sovitko-muottiin/5266404#gs._6vY6wk)
* käytetään vakioina muuttujia (on varmaan tieteellinenkin tapa ilmaista muuttujien lyhenteitä mutta vedin tähän nyt Harry Stetson -menetelmällä jotain...)
>> weight (W) = 85,5
>> standard drink (SD) = 12g
>> body water (BW) vakio = 0,806
>> body water constant male (BWm) = 0,58
>> metabolism constant male (MCm) = 0,015
>> swedish multiplier (SM) = 1.2 (is a factor to convert the amount in grams to Swedish standards set by The Swedish National Institute of Public Health, LÄHDE: https://en.wikipedia.org/wiki/Blood_alcohol_content)
>> permillage conversion (PC) = 10 

Rännin puraisuhistoriasta lasketaan lisäksi aina per palautettava estimaatti
>> elapsed time (ET) = aika juopottelun aloittamisesta (tuntia, esim. 1,25 jne)
>> number of drinks consumed (nSD) = CNT(puraisujen määrä)

Ja sitten vain laskemaan kaavalla:
( ( (BW * nSD * SM)/(BWm * W) ) - MCm * ET ) * PC

Toisin sanoen, kantakyselyn tulisi palauttaa:
* rännin puraisujen määrä
* aika ensipuraisusta
, jotka lisätään kaavaan ja lasketaan estimaatti kysyjälle. 

Jatkokehitysaihiot:
* henkilökohtaiseen profiiliin painolukema
* puraisimeen "musta tuntuu" -kerroin, jossa voisi painottaa puraisun väkevyyttä, esim. 1.5 tarkoittaisi "tämä puraisu on mun mielestä 1.5 keskiketterän vahvuinen". Tai joku elegantimpi slideri tms. 
* lisäksi algoritmi voisi ennustaa, koska seuraava puraisu todennäköisesti tapahtuu puraisuhistorian perusteella, joko ko. rännistä laskien TAI oppivan algoritmin hengessä, jollaa opetusaineistona esim. viimeisen 6 kk:n puraisuaineisto ja puraisujen etäisyys
* ja sitten lisäestimaatti, joka kertoisi, koska on seuraavan kerran odotettavissa, että veren alkoholipitoisuus on nolla

**Comment by ssarkka** [comment]
Niin tämä malli taitaa olla vähän niin kuin

```
  promillet = max(b*n - a*t, 0),
```

jossa a ja b lasketaan monimutkaisesti, n on annosten määrä ensipurasusta lähtien ja t on aika ensipuraisusta. Mutta, jos keritään selviämään, homma alkaa aina alusta. Selvänä ollaan kun ensipuraisusta on kulunut aika n*b/a. Ensipuraisuun rännin perusteella lienee vaan aika max(dt - t1,0) jossa dt on keskimääräinen puraisuväli ja t1 on viime puraisusta kulunut aika. Tässä vapaamuotoisella kielellä tehty idea:

```
class EATME
  // Konffi
  W = 85.5
  SD = 12
  BW = 0.806
  BWm = 0.58
  MCm = 0,015
  SM = 1.2
  PC = 10
  perW = 1.0  

  // Lineaarimallin parametrit (lasketaan aina kun konffi muuttuu)
  a = persW * MCm * PC
  b = (BW * nSD * SM)/(BWm * W)

  promillet()
    T = { hae ajat lähtien ensipuraisusta ja lisää perään nykyinen aika }
    N = { hae puraisujen mutu-kertoimet (oletus aina 1) alkaen ensipuraisusta ja lisää perään 0 }
    p = b*N[1] // indeksi 1 on ensipuraisu
    
    for i = 2,...,len(T) 
      dt = T[i] - T[i-1]
      p = max(p - a*dt, 0) // Promillet hetkellä T[i]
      p = p + b*N[i]

    return p

  selvänä()
    p = promillet()
    return p / a

  puraisutulossa()
    dt = { laske keskimääräinen puraisuväli }
    t1 = { hae viimeisimmästä puraisusta kulunut aika }
    return max(dt - t1, 0)
```

**Comment by ssarkka** [comment]
Matlab-skripti, joka laskee tuloksen:
```

% Puraisujen ajat
times = { ...
'2018-04-25 07:00:00',... % Testi: Tämä palaa pois ennen seuraavaa
'2018-04-25 09:00:00',...
'2018-04-25 09:05:00',...
'2018-04-25 09:19:00',...
'2018-04-25 09:35:00',...
'2018-04-25 09:40:00',...
'2018-04-25 09:45:00',...
'2018-04-25 10:15:00',...
'2018-04-25 10:18:00',...
'2018-04-25 11:40:00',...
'2018-04-25 12:32:00'};

% Puraisujen annosmäärät
num = [ ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1]';

% Henkilökohtainen konfiguraatio
W = 85.5;
SD = 12;
BW = 0.806;
BWm = 0.58;
MCm = 0.015;
SM = 1.2;
PC = 10;
persW = 1.0;

% Laske mallin parametrit
a = persW * MCm * PC
b = (BW * SD * SM)/(BWm * W)
  
% Laske promillet nyt
T = datenum(times); % Päivinä
T = (T - T(1)) * 24; % Tunteina alusta
T = [T; T(end)]; % Nykyhetki lisättynä
N = [num; 0];    % Puraisumäärät ja 0 nykyhetkelle

p = b*N(1); % indeksi 1 on ensipuraisu

for i = 2:numel(T)
    dt = T(i) - T(i-1);
    p = max(p - a*dt, 0); % Promillet hetkellä T(i)
    p = p + b*N(i);
end

t_selva = p / a
dt = mean(diff(T(1:end-1))); % Viimeistä arvoa ei huomioida

fprintf('Promillemäärä nyt on %.1f, selvä olet %.1f tunnin päästä.\n',p,t_selva);
fprintf('Seuraava puraisu on odotettavissa %.1f minuutin päästä.\n',60 * dt);

% Tee graafi promillemääristä
tt = [];
pp = [];
steps = 10;

p = b*N(1); % indeksi 1 on ensipuraisu

for i = 2:numel(T)
    t_list  = linspace(T(i-1),T(i),steps);
    dt_list = t_list - t_list(1);
    p_list = p - a*dt_list;
    p_list(p_list < 0) = 0;
    tt = [tt t_list];
    pp = [pp p_list];
    
    dt = T(i) - T(i-1);
    p = max(p - a*dt, 0); % Promillet hetkellä T(i)
    p = p + b*N(i);
end

plot(tt,pp,'LineWidth',2);
grid on;
xlabel('Aika ensipuraisusta [tuntia]');
ylabel('Alkoholimäärä [promillea]');

print -dpng puraisut;
```
Ja tällainen on tulos:
```
a =

    0.1500


b =

    0.2340


t_selva =

   12.0698

Promillemäärä nyt on 1.8, selvä olet 12.1 tunnin päästä.
Seuraava puraisu on odotettavissa 33.2 minuutin päästä.
```
![puraisut](https://user-images.githubusercontent.com/2706571/40256682-f28c73de-5af3-11e8-8721-f6905b232349.png)

**Comment by tjjalava** [comment]
Tässä sama clojurella:
```clojure
(ns alkoholipros.core
  (:require [java-time :as jt])
  (:gen-class))

(def ^:const W 85.5)
(def ^:const BW 0.806)
(def ^:const SD 12)
(def ^:const BWm 0.58)
(def ^:const MCm (/ 0.015 3600))
(def ^:const SM 1.2)
(def ^:const PC 10)
(def ^:const perW 1.0)

(def ^:const a (* perW MCm PC))
(def ^:const b (/ (* BW SD SM) (* BWm W)))

(println "a =" (* a 3600))
(println "b =" b)

(defn dt [a b]
  (jt/time-between a b :seconds))

(defn format-date [a]
  (jt/format "yyyy-MM-dd HH:mm:ss" a))

(defn calc [prev puraisu]
  (let [alc-pct (+ (max (- (:p prev) (* a (dt (:ts prev) (:ts puraisu)))) 0) (* b (:p puraisu)))]
    (println "Ajanhetkellä" (format-date (:ts puraisu)) "join alkoholia" (:p puraisu) "annoksen verran. Alkoholiprosenttini on" alc-pct "‰")
    (assoc prev :ts (:ts puraisu)
                :p alc-pct)))

(def data
  (let [times [(jt/zoned-date-time 2018 4 25 7)
               (jt/zoned-date-time 2018 4 25 9)
               (jt/zoned-date-time 2018 4 25 9 5)
               (jt/zoned-date-time 2018 4 25 9 19)
               (jt/zoned-date-time 2018 4 25 9 35)
               (jt/zoned-date-time 2018 4 25 9 40)
               (jt/zoned-date-time 2018 4 25 9 45)
               (jt/zoned-date-time 2018 4 25 10 15)
               (jt/zoned-date-time 2018 4 25 10 18)
               (jt/zoned-date-time 2018 4 25 11 40)]]
    (map (fn [ts] {:ts ts :p 1}) times)))

(defn -main [& args]
  (let [{alc-pct :p
         last-ts :ts } (reduce calc {:p 0 :ts (:ts (first data))} data)
        now (jt/zoned-date-time 2018 4 25 12 32)
        final-pct (- alc-pct (* a (dt last-ts now)))]
    (println "Tällä hetkellä (" (format-date now) ") alkoholiprosenttini on" final-pct "‰")
    (println "Selvin päin olen" (/ final-pct (* a 3600)) "tunnin kuluttua")))
```

Esimerkkidatat samat kuin Simolla. Ajon tuloste seuraava:
```
a = 0.15000000000000002
b = 0.2340471869328494
Ajanhetkellä 2018-04-25 07:00:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 0.2340471869328494 ‰
Ajanhetkellä 2018-04-25 09:00:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 0.2340471869328494 ‰
Ajanhetkellä 2018-04-25 09:05:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 0.4555943738656988 ‰
Ajanhetkellä 2018-04-25 09:19:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 0.6546415607985482 ‰
Ajanhetkellä 2018-04-25 09:35:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 0.8486887477313976 ‰
Ajanhetkellä 2018-04-25 09:40:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.070235934664247 ‰
Ajanhetkellä 2018-04-25 09:45:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.2917831215970963 ‰
Ajanhetkellä 2018-04-25 10:15:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.4508303085299457 ‰
Ajanhetkellä 2018-04-25 10:18:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.677377495462795 ‰
Ajanhetkellä 2018-04-25 11:40:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.7064246823956442 ‰
Tällä hetkellä ( 2018-04-25 12:32:00 ) alkoholiprosenttini on 1.5764246823956443 ‰
Selvin päin olen 10.509497882637627 tunnin kuluttua
```

Vähän eri tulokset kuitenkin, tutkitaanpa mistä voisi johtua

**Comment by tjjalava** [comment]
Ah joo, olitkin laskenut myös ton vikan puraisun mukaan.. eli pienellä korjauksella tulos on yhtenevä:
```
a = 0.15000000000000002
b = 0.2340471869328494
Ajanhetkellä 2018-04-25 07:00:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 0.2340471869328494 ‰
Ajanhetkellä 2018-04-25 09:00:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 0.2340471869328494 ‰
Ajanhetkellä 2018-04-25 09:05:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 0.4555943738656988 ‰
Ajanhetkellä 2018-04-25 09:19:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 0.6546415607985482 ‰
Ajanhetkellä 2018-04-25 09:35:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 0.8486887477313976 ‰
Ajanhetkellä 2018-04-25 09:40:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.070235934664247 ‰
Ajanhetkellä 2018-04-25 09:45:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.2917831215970963 ‰
Ajanhetkellä 2018-04-25 10:15:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.4508303085299457 ‰
Ajanhetkellä 2018-04-25 10:18:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.677377495462795 ‰
Ajanhetkellä 2018-04-25 11:40:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.7064246823956442 ‰
Ajanhetkellä 2018-04-25 12:32:00 join alkoholia 1 annoksen verran. Alkoholiprosenttini on 1.8104718693284936 ‰
Tällä hetkellä ( 2018-04-25 12:32:00 ) alkoholiprosenttini on 1.8104718693284936 ‰
Selvin päin olen 12.069812462189955 tunnin kuluttua
```

**Comment by samiheinanen** [comment]
Kelpo rautalankaa! Tuossa alkaa olla perusraportointia varten tarvittavat elementit kasassa. Teen rapsoista erilliset issuet.

**Comment by tjjalava** [comment]
Graafinen osasto HOX: nyt tarvittaisiin vähän (peli)silmää käyttöliittymää varten. Eli miten näytetään kompaktisti puraisijan rännin ja jurrin tila. 

Tällä hetkellä työversiona on tällaista:
<img width="798" alt="screenshot 2018-08-20 12 11 56" src="https://user-images.githubusercontent.com/886267/44331542-6440de80-a472-11e8-9016-d3c5d51a41d8.png">

ja
<img width="792" alt="screenshot 2018-08-20 12 05 56" src="https://user-images.githubusercontent.com/886267/44331554-6f940a00-a472-11e8-9541-d48ba04f839b.png">

Näkisin, että ton rännitilan voisi visualisoida jonkinlaisilla liikennevalo-buttoneilla tms. (vihreä: ränni päällä, keltainen: ränni meinaa loppua, lisää viinaa, punainen: ränni katki) (ehkä myös pitää miettiä tota ränni "päällä"/"katki"-sananvalintaa)

**Comment by samiheinanen** [comment]
Yhdistelin monenlaista kamaa... ehkä pihvinä tuo "Sparkline last 24h", joka näyttää rendin, puraisut pisteinä (jos halutaan), kolmiosymboli kertomaan mikä on rännin tila nyt sekä tuon prosentin tilalle promillelukema. Sitten tuon promillen tekstiselityksenä vois feidaa. 

Lisäksi vaihdoin pystyyn nuo monivalinnat, otin otsikot tekstilaatikoilta pois, kun kerran placeholdereissa on tekstit. Puraise napin siirsin tuohon oikealle vapaaselitysboksin viereen. Ensituntumalta ei tullut isoa vitutusta tuota kokeillessa. 

Sorsaa ei ole, tämä on puhtaasti powerpoint-harjoituksena tehty...

![pp_visuehdotus](https://user-images.githubusercontent.com/12933669/44335256-8b9ca900-a47c-11e8-824e-522dda250fa0.png)

**Comment by tjjalava** [comment]
joo, hyvä. Pari kommenttia vielä:
Viime puraisussa on IMHO kiva kertoa myös viikonpäivä. Saahan sen toki päivämäärästäkin selville, jos jaksaa laskea. No, pikku juttu, voihan se myös laittaa vaikka tooltippiin, jos vielä liikaa tilaa ui:ssa

Puraisutyyppi-valitsin katoaa tyystin, koska tyyppejä ei enää tilastoida, ainoastaan rännit. Sen sijaan postfestum-puraisuille pitäisi lisätä päivämäärä-valitsin.. tai vaihtoehtoisesti numerovalitsin "kuinka monta tuntia sitten"

Johonkin pitäisi vielä tunkata myös puraisun alkoholimäärävalitsin (grammoina). Ehkä joku liukuvalitsin, jossa 12 grammaa on valittu oletukseksi ja jota voi sitten oman mutu-arvion perusteella hilata ylös tai alaspäin?

Toi kuvaaja jäänee myöhemmin toteutettavaksi, sen tilalle voisi ensi alkuun kyllä laittaa jonkin ränni-ilmaisimen?

**Comment by samiheinanen** [comment]
joo, voisin noitten pohjalta tunkata vielä yhden vedoksen myöhemmin tänään

**Comment by samiheinanen** [comment]
versio 0.2 for review

![image](https://user-images.githubusercontent.com/12933669/44445123-79d81480-a5e8-11e8-9048-b9480569661a.png)

**Comment by tjjalava** [comment]
tossa on vähän likkaa kamaa nyt, menee vähän ahtaaksi mobiilinäytöllä. Noi ikonit ainakin pois. Muuten kyllä hyvä

**Comment by samiheinanen** [comment]
v0.3
![image](https://user-images.githubusercontent.com/12933669/44569534-68773f80-a783-11e8-8715-adf3c74f56f7.png)

slideri löytys näköjään myös vaikka tuolta: https://codepen.io/trevanhetzel/pen/rOVrGK
