### ISSUE TITLE
Postfestum puraisuille lisäparametri

### ISSUE THREAD

**Issue by samiheinanen** [KosmosRy/puraisin#28]
Käyttäjänä haluan, että voin täsmäyttää postfestum-puraisun minuutilleen oikeaan ajanhetkeen. Kun valitsen postfestum, saan näkyviin lisäkentän, jossa voin antaa offsetin taaksepäin esim. minuutteina. 

Näin tietokantaan saataisiin raportointihetki sekä oikea hetki puraisulle laskettua. Vaatii tietokantamuutoksen puraisu-tauluun, uusi sarake esim. "poffset"

**Comment by tjjalava** [comment]
Miksi ei vain laske käyttäjän offsetista todellinen puraisuhetki ja tallenna se normaalisti timestamp-sarakkeeseen?

**Comment by tjjalava** [comment]
Vai onko raportointihetkellä jotain käyttöä?

**Comment by samiheinanen** [comment]
Koska siten voidaan julkaista tulevaisuudessa postfestum häpeälistaa

**Comment by tjjalava** [comment]
Postfestum-tieto sinne toki tallennetaan jo nyt, eli lähinnä kysymys on onko raportointiajalla mitään käyttöä. Itse en keksi..

**Comment by samiheinanen** [comment]
Tilastollisen tarkkuden parantaminen on tärkein, eli kyllä se aikaleiman tuunaus olisi ihan ok. "Miten paljon myöhässä raportoin" ei tosiaan ole ehkä tärkein rapsa. Eli sovitaanko että modataan aikaleimaa?
