### ISSUE TITLE
Osoite heristävä-appi.kosmosry.fi ei toimi

### ISSUE THREAD

**Issue by tjjalava** [KosmosRy/puraisin#3]
Osoite http://heristävä-appi.kosmosry.fi ohjaa oikein herokuun, mutta näyttää vain oletus-etusivua. Johtunee siitä, että herokuun pitäisi konffata tuo ”virallinen” osoite oletusosoitteeksi. Onnistunee herokun asetuksista

**Comment by tjjalava** [comment]
täältä ohjeet: https://devcenter.heroku.com/articles/custom-domains

**Comment by samiheinanen** [comment]
lisätty DNS target xn--heristv-appi-lcbb.kosmosry.fi.herokudns.com, nyt toimii http-kekkosena osoitteessa http://heristävä-appi.kosmosry.fi
