### ISSUE TITLE
Nopeuden lisääminen coordinates-tietoon

### ISSUE THREAD

**Issue by stoivane** [KosmosRy/puraisin#36]
Lisätään nopeustieto (geolocation-APIn speed & heading) mukaan coordinates-objektiin.
Vauhtitietoa voidaan käyttää esimerkiksi tunnistettaessa lentokonepuraisu (katso #35), ja onhan se kivaa lisätietoa tilastokatsauksiin y.m. y.m. y.m.!

**Comment by tjjalava** [comment]
Fixed #37
