### ISSUE TITLE
Herokussa väärä sertifikaatti

### ISSUE THREAD

**Issue by tjjalava** [KosmosRy/puraisin#4]
Jos käyttää puraisijaa osoitteen https://heristävä-appi.kosmosry.fi kautta, saa ilmoituksen väärästä sertifikaatista. Herokuun pitäisi konffata sertifikaatti kyseiselle hostille, tai vaihtoehtoisesti wildcard-sertifikaatti domainille kosmosry.fi.

**Comment by tjjalava** [comment]
Ilmeisesti ilmaisessa herokussa ei ole mahdollista käyttää omia sertifikaatteja. Eli vaihtoehdoiksi jää 
- käyttää puraisinta kekkosena (ok niin kauan kun ei välitetä mitään käyttäjätunnuksia tms.)
- maksaa herokun hobby-lisenssi (~7$/kk)
- siirtää sovellus muulle alustalle, esim. AWS:ään

**Comment by samiheinanen** [comment]
jääköön toistaiseksi pohdintaan kunnes päätän, siirtyäkö omalle pannulle tuskailemaan kaiken maailman ympäristöjen kanssa.

**Comment by tjjalava** [comment]
vertaistukea AWS:n päässä kyllä löytyy, siellä voinet keskittyä tunkkamaan pelkästään koodia, kaikki muu hoituu "talon puolesta" 😉

**Comment by tjjalava** [comment]
eipä enää ajankohtainen sovelluksen siirryttyä aws:ään
