### ISSUE TITLE
Raportti-preview & köyhän miehen slack-integraatio

### ISSUE THREAD

**Issue by ssarkka** [KosmosRy/puraisin#5]
Olisi cool jos puraisin näyttäisi jossain alhaalla sen generoitavan puraisuraportin koko ajan kun valikoista vedetään vaihtoehtoja. Ettei raportti mene ihan yllätyksenä.
Jos tämä puraisuraportti-preview olisi vielä sellaisessa tekstikentässä, josta voidaan kopioida tekstiä, saadan tällä toteutettua myös köyhän miehen slack-integraatio eli copy-paste. Hyvä puoli siinä on, että siihen ei tarvita minkäänlaisia autentikointeja jne.

**Comment by tjjalava** [comment]
näkyykö tää slackissa?
