### ISSUE TITLE
puraisin.backup vienti aws-possuun

### ISSUE THREAD

**Issue by samiheinanen** [KosmosRy/puraisin#6]
ladattu file uploadilla .backup, pitäs mennä restorella ja jos ei mee, pitää loitsia ddl:

-- CREATE DATABASE puraisin;

-- Table: public.puraisu
-- DROP TABLE public.puraisu;

CREATE TABLE public.puraisu
(
    type character varying(512) COLLATE pg_catalog."default" NOT NULL,
    content character varying(512) COLLATE pg_catalog."default" NOT NULL,
    location character varying(512) COLLATE pg_catalog."default" NOT NULL,
    source character varying(32) COLLATE pg_catalog."default" NOT NULL,
    biter character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "timestamp" timestamp with time zone DEFAULT now()
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.puraisu
    OWNER to [db_rw_uid_here];

**Comment by samiheinanen** [comment]
datoilla ei nyt niin väliä, niitä tulee sitten testatessa. ajattelin tunkata myöhemmin vielä taulut
* bitetype(id, type)
* content(id, freetext)
* location(id, lat, lon, freetext)
* user(id, pass, name)

ja varsinainen puraisutaulu sisältaisi vain viittaukset tuttuun, eli em. tauluihin ja noissa tauluissa olisi vain uniikit tietosisällöt. ehkä hivenen teoreettista näillä volyymeilla mutta lähempänä 3NF kuitenkin, vaikkei sinne ihan taida yltääkään. frontissa tsekataan vain vapaahaulla sitten löytyskö jo valmista vaihtoehtoa. locationin osalta freetext riittäisi minimiksi, halutessaa geoloc:n kautta otettaisiin lat/lon.

**Comment by tjjalava** [comment]
valmis
