### ISSUE TITLE
Geolokaatio käyttöön sijaintivalinnassa

### ISSUE THREAD

**Issue by stoivane** [KosmosRy/puraisin#8]
Sijaintiin pitää lisätä valittavaksi maantieteellinen sijainti.

Koordinaatit saadaan W3C:n Geolocation APIsta. Kannattaa lukea esim. https://code.tutsplus.com/tutorials/an-introduction-to-the-geolocation-api--cms-20071 (vähän polveilevampi tutoriaali, mutta vaikuttaa selittävän homman aika perusteellisesti).

Geolocation APIn käytössä kannattaa huomata, että sijaintitieto saadaan pienellä viiveellä ja se voi tarkentua ajan mittaan. Tämän takia API perustuu callbackien käyttöön (esim. `successCallback` em. tutoriaalissa).

Lähtisin rakentamaan toteutusta `watchPosition`-funktion päälle. Tällöin sijainti voisi päivittyä itsekseen taustalla käyttäjän toimista riippumatta (voidaan ja kannattaneekin päivittää samalla myös käyttäjälle näkyviä koordinaatteja), ja submitin yhteydessä napataan senhetkinen sijainti POSTiin mukaan.

Halutessaan voi miettiä myös, asetetaanko sijainnin tarkkuudelle jokin hyväksyttävä alaraja vai hyväksytäänkö kaikki arvot. Jossain tilanteessahan APIn palauttama tarkkuus voi olla kilometrien tai jopa kymmenien kilometrien luokkaa.

**Comment by samiheinanen** [comment]
vaikuttaisi vallan suoraviivaiselta. lupa kysyttäneen vain kerran, muuten käyttökokemus häiriintyy aina puraisimessa vieraillessa. wathPosition varmasti ok, tuotetaan se formin kenttään, mikäli paikannus valittuna radio-ryhmässä. paikannusvalinnasta poistuminen katkaisee sijainnin kysynnän? vai pidetäänkö "haku päällä" koko ajan. olisi tosiaan kätevää hoitaa paikannus jo taustalla ja tarjota sitä. lisäksi ehdotus: entä jos tallennetaan "position" omana kenttänään ja "location" olisi kuvaavaa, kategorista tietoa absoluuttisen position lisäksi?

**Comment by tjjalava** [comment]
minä ehdottaisin sellaista, että lokaatio haetaan (mikäli käyttäjä on sallinut) aina taustalla ja välitetään lokaatiokentässä. Jos käyttäjä lisäksi antaa tarkentavan, kirjallisen lokaatioarvion, näytetään koordinaattilokaatio vaikkapa suluissa käyttäjän syöttämän paikan perässä. Tähän tyyliin:

Käyttäjä ei syötä lokaatiotietoa:
`ep;sahtia;60.18999,24.96110 +-60m`

käyttäjä syöttää lokaatiotiedon:
`ep;sahtia;töissä (60.18999,24.96110 +-60m)`

tjsp

**Comment by stoivane** [comment]
Kannatan Jallun ehdotusta. Ja tarkkuuteen vielä plus-miinuksen merkiksi `±` niin hyvä tulee. Toi desimaaliasteet muodossa `60.18999,24.96110` on copy-paste-siirrettävyyden kannalta varmasti paras muotoilu.

**Comment by tjjalava** [comment]
ja näin tapahtui
